"use client";

import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { MOCK_RECOMMENDATION } from "@/lib/mock-data";
import { useDashboardStore } from "@/stores/dashboard-store";
import {
  AlertTriangle,
  TrendingUp,
  Lightbulb,
  Target,
  Clock,
  Sparkles,
} from "lucide-react";
import type { LLMRecommendation, RecommendationContent } from "@/types";

const priorityConfig = {
  high: { color: "negative" as const, icon: AlertTriangle, label: "High Priority" },
  medium: { color: "warning" as const, icon: Target, label: "Medium Priority" },
  low: { color: "secondary" as const, icon: Clock, label: "Low Priority" },
};

function RecommendationCard({ recommendation, isLatest }: { recommendation: LLMRecommendation; isLatest?: boolean }) {
  const rec: RecommendationContent = recommendation.summary_text;

  return (
    <Card className={isLatest ? "ring-2 ring-primary/30" : ""}>
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="text-lg flex items-center gap-2">
              AI Recommendations
              {isLatest && (
                <Badge className="bg-primary/10 text-primary border-primary/20 text-[10px]">
                  <Sparkles className="h-3 w-3 mr-1" />
                  Latest Run
                </Badge>
              )}
            </CardTitle>
            <CardDescription>
              Generated by Claude Sonnet 4.6 — {new Date(recommendation.generated_at).toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" })}
            </CardDescription>
          </div>
          <Badge variant="outline" className="text-xs">
            {recommendation.run_type === "daily" ? "Daily Run" : "Mid-Month Adjustment"}
          </Badge>
        </div>
      </CardHeader>
      <CardContent className="space-y-6">
        <section>
          <h4 className="text-sm font-semibold text-primary mb-2 flex items-center gap-1.5">
            <Lightbulb className="h-4 w-4" />
            Executive Summary
          </h4>
          <p className="text-sm text-muted-foreground leading-relaxed">
            {rec.executive_summary}
          </p>
        </section>

        <Separator />

        <section>
          <h4 className="text-sm font-semibold text-primary mb-3 flex items-center gap-1.5">
            <TrendingUp className="h-4 w-4" />
            Key Trends
          </h4>
          <ul className="space-y-2">
            {rec.trends.map((trend, i) => (
              <li key={i} className="flex gap-2 text-sm text-muted-foreground">
                <span className="text-primary mt-0.5 shrink-0">{"\u2022"}</span>
                {trend}
              </li>
            ))}
          </ul>
        </section>

        <Separator />

        <section>
          <h4 className="text-sm font-semibold text-red-600 mb-3 flex items-center gap-1.5">
            <AlertTriangle className="h-4 w-4" />
            Anomalies Detected
          </h4>
          <ul className="space-y-2">
            {rec.anomalies.map((anomaly, i) => (
              <li key={i} className="flex gap-2 text-sm text-muted-foreground">
                <span className="text-red-500 mt-0.5 shrink-0">!</span>
                {anomaly}
              </li>
            ))}
          </ul>
        </section>

        <Separator />

        <section>
          <h4 className="text-sm font-semibold text-primary mb-3 flex items-center gap-1.5">
            <Target className="h-4 w-4" />
            Actionable Recommendations
          </h4>
          <div className="space-y-4">
            {rec.recommendations.map((r, i) => {
              const config = priorityConfig[r.priority];
              const Icon = config.icon;
              return (
                <div key={i} className="rounded-lg border border-border/30 p-4 space-y-2">
                  <div className="flex items-start justify-between gap-2">
                    <div className="flex items-center gap-2">
                      <Icon className="h-4 w-4 shrink-0" />
                      <span className="text-sm font-medium">{r.action}</span>
                    </div>
                    <div className="flex gap-1.5 shrink-0">
                      <Badge variant={config.color}>{config.label}</Badge>
                      <Badge variant="outline">{r.category}</Badge>
                    </div>
                  </div>
                  <p className="text-xs text-muted-foreground pl-6">{r.rationale}</p>
                  <p className="text-xs font-medium text-primary pl-6">
                    Expected Impact: {r.expected_impact}
                  </p>
                </div>
              );
            })}
          </div>
        </section>

        <Separator />

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <section className="rounded-lg bg-muted p-4">
            <h4 className="text-sm font-semibold text-foreground mb-2">vs Baseline Plan</h4>
            <p className="text-xs text-muted-foreground leading-relaxed">
              {rec.baseline_comparison}
            </p>
          </section>
          <section className="rounded-lg bg-muted p-4">
            <h4 className="text-sm font-semibold text-foreground mb-2">vs Ambitious Plan</h4>
            <p className="text-xs text-muted-foreground leading-relaxed">
              {rec.ambitious_comparison}
            </p>
          </section>
        </div>
      </CardContent>
    </Card>
  );
}

export function RecommendationsPanel() {
  const { latestRecommendation } = useDashboardStore();

  return (
    <div className="space-y-6">
      {latestRecommendation && (
        <RecommendationCard recommendation={latestRecommendation} isLatest />
      )}
      <RecommendationCard recommendation={MOCK_RECOMMENDATION} />
    </div>
  );
}
